### Team Beta ETL Project Proposal
Team Beta: Steve Kennedy, Camilla Inhapim, Michael Goff, Jason Hanlin
Topic: Major League Baseball
Task: ETL



Team Beta proposes to extract two data sources with a focus on Major League Baseball statistics.  
Work will be divided as follows:
•	Extraction – Jason and Steve
•	Transformation – Mike and Camilla
•	Load – Marlon

The links for the project are as follows:
•	https://github.com/tenntully/Project2-TeamBeta.git
•	https://www.seanlahman.com/baseball-archive/statistics/
•	https://www.kaggle.com/datasets/open-source-sports/baseball-databank

Our transformed data will be loaded to Postgres.

In [2]:
import pandas as pd

#Apply global formatting to all floats to only show hundredths
pd.options.display.float_format = '{:,.2f}'.format

#Load school and student data sets
teams_data_load = "Resources/Teams.csv"
franchise_data_load = "Resources/TeamsFranchises.csv"

#Read data into pandas DF
teamsData = pd.read_csv(teams_data_load)
franchiseData = pd.read_csv(franchise_data_load)

#Combine data into a single file; combine on school_name
team_data_full = pd.merge(teamsData, franchiseData, how="left", on=["franchID", "franchID"])
#team_data_full.head()
team_data_full.columns

Index(['yearID', 'lgID', 'teamID', 'franchID', 'divID', 'Rank', 'G', 'Ghome',
       'W', 'L', 'DivWin', 'WCWin', 'LgWin', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'CS', 'HBP', 'SF', 'RA', 'ER', 'ERA',
       'CG', 'SHO', 'SV', 'IPouts', 'HA', 'HRA', 'BBA', 'SOA', 'E', 'DP', 'FP',
       'name', 'park', 'attendance', 'BPF', 'PPF', 'teamIDBR',
       'teamIDlahman45', 'teamIDretro', 'franchName', 'active', 'NAassoc'],
      dtype='object')

In [3]:
#drop columns
team_data_full.drop(columns=['lgID', 'divID', 'Ghome', 'teamIDlahman45', 'teamIDretro', 'NAassoc'])

,yearID,teamID,franchID,Rank,G,W,L,DivWin,WCWin,LgWin,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,franchName,active
0,1871,BS1,BNA,3,31,20,10,NaN,NaN,N,...,24,0.83,Boston Red Stockings,South End Grounds I,NaN,103,98,BOS,Boston Red Stockings,NaN
1,1871,CH1,CNA,2,28,19,9,NaN,NaN,N,...,16,0.83,Chicago White Stockings,Union Base-Ball Grounds,NaN,104,102,CHI,Chicago White Stockings,NaN
2,1871,CL1,CFC,8,29,10,19,NaN,NaN,N,...,15,0.82,Cleveland Forest Citys,National Association Grounds,NaN,96,100,CLE,Cleveland Forest Citys,NaN
3,1871,FW1,KEK,7,19,7,12,NaN,NaN,N,...,8,0.80,Fort Wayne Kekiongas,Hamilton Field,NaN,101,107,KEK,Fort Wayne Kekiongas,NaN
4,1871,NY2,NNA,5,33,16,17,NaN,NaN,N,...,14,0.84,New York Mutuals,Union Grounds (Brooklyn),NaN,90,88,NYU,New York Mutuals,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3010,2022,SLN,STL,1,162,93,69,Y,N,N,...,181,0.99,St. Louis Cardinals,Busch Stadium III,"3,320,551.00",94,94,STL,St. Louis Cardinals,Y
3011,2022,TBA,TBD,1,162,86,76,N,Y,N,...,110,0.98,Tampa Bay Rays,Tropicana Field,"1,128,127.00",95,93,TBR,Tampa Bay Rays,Y
3012,2022,TEX,TEX,4,162,68,94,N,N,N,...,143,0.98,Texas Rangers,Globe Life Field,"2,011,361.00",100,101,TEX,Texas Rangers,Y
3013,2022,TOR,TOR,2,162,92,70,N,Y,N,...,120,0.99,Toronto Blue Jays,Rogers Centre,"2,653,830.00",100,100,TOR,Toronto Blue Jays,Y
3014,2022,WAS,WSN,5,162,55,107,N,N,N,...,126,0.98,Washington Nationals,Nationals Park,"2,026,401.00",94,96,WSN,Washington Nationals,Y